### ISSUE TITLE
请问本地测试正常，部署到github pages缺失css，什么问题？

### ISSUE THREAD

**Issue by aceking10** [calfzhou/gocalf-blog#1]
浏览器解析比localhost:8000少了 style.min.css,调试信息：GET /theme/css/style.min.css?93135f3f

**Comment by calfzhou** [comment]
这个文件时[assets](https://github.com/getpelican/pelican-plugins/tree/master/assets)这个插件生成的，看下你是否加了这个插件呢。

**Comment by aceking10** [comment]
解决啦，siteurl的问题。主题很不错，正在使用中。^_^
